name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make cache-folders build composer-install tests
